#!/bin/bash
#SBATCH --job-name pre-trimming           # Name for your job
#SBATCH --nodes=1                         # node count
#SBATCH -c 1                              # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --time=01:00:00                   # Total run time limit in HH:MM:SS
#SBATCH --partition=fast                  # Partition to submit
#SBATCH --error=logs/01-FastQC_%a.%A.err  # STDERR file
#SBATCH --output=logs/01-FastQC_%a.%A.out # STDOUT file 
#SBATCH --mail-type=end                   # send email when job ends
#SBATCH --mail-user=luciamartinfernandez99@gmail.com # this is the email you wish to be notified at
#SBATCH --array=1-234                     # Array range and number of simultanous job

# Remember to create logs directory on terminal
# mkdir logs

# Activate environment 
# source $HOME/miniconda3/bin/activate

# Load required modules
ml FastQC 

# Search all the fastq files from the "data" directory and generate the array
file=$(ls /home/lmartin/SRV_RyC/00-raw_reads/*.gz|sed -n ${SLURM_ARRAY_TASK_ID}p)

# 1. Run quality analysis on each fastq file
fastqc -o /home/lmartin/SRV_RyC/01-pre_fastqc/ $file

# 2. Run multiqc to create summary report
# multiqc --force ./




